- name: Place apt sources file
  copy: src=google-chrome.list dest=/etc/apt/sources.list.d

- name: Run apt update and install
  apt: name=google-chrome-stable update_cache=yes allow_unauthenticated=yes

