---
- name: Supress default xconsole and set bg color
  shell: 'echo xsetroot -solid black > /etc/X11/xdm/Xsetup_0'

# Specify a pkg flavour with '--no_x11' or '--' for the default flavour
- name: Install chromium
  openbsd_pkg: name=chromium state=present

- name: Install python-3.5.2
  shell: 'pkg_add -I -D unsigned python%3.5'

- name: Install ImageMagick
  shell: 'pkg_add -I -D unsigned ImageMagick'

- name: reverseVideo thing on OpenBSD
  lineinfile:
    dest: /home/mike/.Xdefaults
    state: present
    line: 'XTerm*reverseVideo: true'
