---
- name: Derive OpenBSD version
  shell: uname -r
  register: uname_version_result

- name: Derive OpenBSD arch
  shell: uname -m
  register: uname_arch_result

- name: Set openbsd_version (overridden by var files)
  set_fact:
    openbsd_version: "{{uname_version_result.stdout}}"
  when: openbsd_version is not defined

- name: Set openbsd_arch
  set_fact:
    openbsd_arch: "{{uname_arch_result.stdout}}"

- name: Setup PKG_PATH
  become: yes
  lineinfile:
    dest: /etc/pkg.conf
    create: yes
    state: present
    line: "installpath = http://ftp3.usa.openbsd.org/pub/OpenBSD/{{openbsd_version}}/packages/{{openbsd_arch}}"

# Specify a pkg flavour with '--no_x11' or '--' for the default flavour
- openbsd_pkg: name=vim--no_x11 state=present
- openbsd_pkg: name=git-- state=present

# TODO Refactor these out to a generic/common roll appicable across unix like OSes.
- name: Setup /home/mike/src
  file: path=/home/mike/src state=directory

- name: Fetch dotfiles repo
  become_user: mike
  git: repo=https://github.com/mikeputnam/dotfiles.git dest=/home/mike/src/dotfiles force=yes

- name: Discover dotfiles in /home/mike
  find: paths="/home/mike/src/dotfiles" patterns="*.*" hidden=true
  register: dotfile_results

- name: Create symlinks in /home/mike
  file: src={{item.path}} dest=/home/mike/{{item.path | basename}} owner=mike group=mike force=yes state=link
  with_items: dotfile_results.files
# TODO Refactor

- name: Source .kshrc via .profile on OpenBSD
  lineinfile:
    dest: /home/mike/.profile
    state: present
    line: 'export ENV=$HOME/.kshrc'

- name: FIXME reverseVideo thing on OpenBSD
  lineinfile:
    dest: /home/mike/.Xdefaults
    state: present
    line: 'XTerm*reverseVideo: true'

