---
- name: Install vim
  shell: 'pkg_add -I -D unsigned vim--no_x11'

- name: Install git
  shell: 'pkg_add -I -D unsigned git'

- name: Source .kshrc via .profile on OpenBSD
  lineinfile:
    dest: /home/mike/.profile
    state: present
    line: 'export ENV=$HOME/.kshrc'

