---
# This role applies system updates
#
# Usage: ansible-playbook -vv -u <user> --ask-become-pass --ask-vault-pass apply_updates.yml

- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_os_family }}

- hosts: os_Debian
  gather_facts: False
  become: yes
  tasks:
    - apt: update_cache=yes upgrade=yes
  roles:
    - { role: common }

- hosts: os_Darwin
  gather_facts: false
  become: yes
  tasks:
    - command: softwareupdate --install --all
    - homebrew: update_homebrew=yes upgrade_all=yes

- hosts: os_Windows
  gather_facts: false
  tasks:
    - win_chocolatey: name=PSWindowsUpdate state=present
    - win_updates: category=security

- hosts: os_Debian
  gather_facts: false
  become: yes
  tasks:
    - name: Check for reboot hint
      shell: if [ $(readlink -f /vmlinuz) != /boot/vmlinuz-$(uname -r) ]; then echo 'reboot'; fi
      ignore_errors: true
      register: reboot_hint

    - name: Rebooting...
      command: shutdown -r now "New kernel installed"
      async: 0
      poll: 0
      ignore_errors: true
      when: reboot_hint.stdout.find("reboot") != -1

    - name: Wait for reboots to complete
      pause: minutes=3
      when: reboot_hint.stdout.find("reboot") != -1

    - name: Show running kernel
      shell: uname -a
      register: running_kernel
