---
# This playbook sets up minimum/base config for OpenBSD machines.
# Assumes that desktop machines are running -current.
#
# Usage:
# ansible-playbook -vv -i hosts --vault-password-file ~/.vault2113.txt provision_openbsd.yml --extra-vars "openbsd_version=snapshots openbsd_arch=amd64"
- name: Provision OpenBSD servers
  hosts: openbsd_servers
  become: yes
  roles:
    - { role: openbsd_common }
    - { role: dotfiles }

- name: Provision OpenBSD desktops
  hosts: openbsd_desktops
  become: yes
  gather_facts: no # disabled so we can ensure python2 is available first
  pre_tasks:
    - name: Setup pkg.conf so we can install packages
      raw: "ksh -c 'echo \"installpath = http://ftp3.usa.openbsd.org/pub/OpenBSD/{{ openbsd_version }}/packages/{{ openbsd_arch }}\" > /etc/pkg.conf'"
    - name: Install python2 for Ansible to use
      raw: "pkg_add -I -D unsigned python%2.7"
    - action: setup # ok NOW gather facts
  roles:
    - { role: openbsd_common }
    - { role: dotfiles }
    - { role: openbsd_desktops }


