---
- name: Install build-essential
  apt: pkg=build-essential

- name: Install aptitude
  apt: pkg=aptitude

- name: Install vim
  apt: pkg=vim

- name: Set EDITOR vim
  alternatives: name=editor path=/usr/bin/vim.basic

- name: Install xterm
  apt: pkg=xterm

- name: Set xterm default graphical terminal
  alternatives: name=x-terminal-emulator path=/usr/bin/xterm

- name: Install tmux
  apt: pkg=tmux

- name: Install git
  apt: pkg=git

- name: Install ntp
  apt: pkg=ntp
