---
- name: Install build-essential
  apt: pkg=build-essential

- name: Install aptitude
  apt: pkg=aptitude

- name: Install vim
  apt: pkg=vim

- name: Install tmux
  apt: pkg=tmux

- name: Install git
  apt: pkg=git

- name: Install ntp
  apt: pkg=ntp
